### ISSUE TITLE
Dataset incomplete in Module 4

### ISSUE THREAD

**Issue by lrenzi1000** [PacktPublishing/A-Practical-Approach-to-Timeseries-Forecasting-using-Python#2]
Dataset air_pollution.csv with missing columns in GitHub.
Only first three columns are available: date, pollution_today, and dew

**Comment by Sonakshis** [comment]
Hi @lrenzi1000 
We have update the file: https://github.com/PacktPublishing/A-Practical-Approach-to-Timeseries-Forecasting-using-Python/blob/63435f413a099d7948acb3059f0dc8825832ea43/4%20-%20Data%20Processing%20for%20Timeseries%20Forecasting/Notebook/air_pollution.csv
